# SPDX-License-Identifier: MIT

name: Add to project

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  add-to-project:
    name: Add to project
    if: |
      ! github.event.repository.fork
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
      PROJECT: "uchikoshi-fes.jp-2022"
    steps:
      - run: |
          gh issue edit $NUMBER --add-project $PROJECT
