# SPDX-License-Identifier: MIT

name: Fix branch

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - "main"
      - "develop"
jobs:
  into_main:
    if: |
      startsWith(github.head_ref, 'hotfix/') && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: gh pr edit --base main
  into_develop:
    if: |
      ! ( startsWith(github.head_ref, 'hotfix/') || github.head_ref == 'develop' ) && github.base_ref == 'main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: gh pr edit --base develop
