name: lint

on: push

jobs:
  convert:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
